apiVersion: v1
data:
  branch: demo-mq-v2-jeffdmgit
  host: github.com
  org: jeffdmgit
  owner: jeffdmgit
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops
  url: https://github.com/jeffdmgit/multi-tenancy-gitops.git
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
  namespace: ci
